config/routes.rb
Rails.application.routes.draw do
  root 'issues#index'

  resources :issues, only: %i(new create show index)
  resources :categories, only: %i(edit update show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint           not null, primary key
#  description :text(65535)
#  name        :string(50)       not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_categories_on_name  (name) UNIQUE
#
class Category < ApplicationRecord
  has_many :issues, dependent: :destroy

  validates :name, uniqueness: true, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 500 }
end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id          :bigint           not null, primary key
#  text        :text(65535)      not null
#  title       :string(100)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#
# Indexes
#
#  index_issues_on_category_id  (category_id)
#
class Issue < ApplicationRecord
  belongs_to :category

  validates :title, presence: true, length: { maximum: 100 }
  validates :text, presence: true, length: { maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def edit
    @category = Category.find(params[:id])
  end

  def update
    if Category.update(category_params)
      redirect_to category_path, flash: { notice: '更新に成功しました' }
    else
      flash.now[:alert] = '更新に失敗しました'
      render :edit
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:description)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def new
    @issue = Issue.new
  end

  def create
    category = Category.find_or_initialize_by(name: issue_params[:category_name])
    issue = category.issues.new(title: issue_params[:title], text: issue_params[:text])

    if category.save
      redirect_to issue, flash: { notice: '登録に成功しました' }
    else
      flash.now[:alert] = '登録に失敗しました'
      render :new
    end
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def index
    @categories = Category.eager_load(:issues)
  end

  private

  def issue_params
    params.require(:issue).permit(:category_name, :title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.slim
- content_for :title do
  カテゴリ編集

h2
  = @category.name

= form_with model: @category, local: true do |f|
  p
    = f.text_area :description, placeholder: '500文字以内', size: '50x10'
  p
    = f.submit '更新'

hr
= link_to '戻る', category_path(@category.id)

app/views/categories/show.html.slim
- content_for :title do
  カテゴリ一覧

h2
  = @category.name

p
  = @category.description || '説明未登録'
p
  = link_to 'カテゴリ説明編集', edit_category_path(@category.id)

- @category.issues.each do |issue|
  ul
    li
      = issue.title

hr
= link_to '戻る', issues_path

app/views/issues/index.html.slim
- content_for :title do
  課題管理

p
  = link_to '新規登録', new_issue_path

- @categories.each do |category|
  ul
    li
      h2
        = link_to category.name, category_path(category.id)

      - category.issues.each do |issue|
        ul
          li
            = link_to issue.title, issue_path(issue.id)
          ul
            li
              = l(issue.created_at.in_time_zone('Tokyo'), format: :date)

app/views/issues/new.html.slim
- content_for :title do
  課題登録

= form_with model: @issue, scope: :issue, local: true do |f|
  p
    = f.label 'カテゴリ名'
    br
    = f.text_field :category_name, placeholder: '50文字以内', size: '50'
  p
    = f.label 'タイトル'
    br
    = f.text_field :title, placeholder: '100文字以内', size: '50'
  p
    = f.label '本文'
    br
    = f.text_area :text, placeholder: '1000文字以内', size: '100x20'
  p
    = f.submit '登録', size: '50'

hr
  = link_to '戻る', issues_path, class: 'button'

app/views/issues/show.html.slim
- content_for :title do
  課題詳細

h2
  = @issue.title
p
  = @issue.category.name
p
  = @issue.text

hr
= link_to '戻る', issues_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsPractice
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    h1
      = yield :title

    - flash.each do |key, value|
      = content_tag :div, value, class: key, style: 'color: red'

    hr

    = yield